#!/usr/bin/env python

import sys
import subprocess

print("🔍 Git Secret Scanner Running...")

result = subprocess.run(
    ["python", "backend/main.py"],
    capture_output=True,
    text=True
)

print(result.stdout)

if result.returncode != 0:
    print("❌ Commit blocked due to secrets")
    sys.exit(1)

sys.exit(0)
